// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: vehicle.proto

package vehiclepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	commonpb "proto/commonpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Telemetry sent from vehicle to server
type Telemetry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleId      uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	TimestampMs    int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Lat            float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon            float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	SpeedKmh       float32                `protobuf:"fixed32,5,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	BatteryPercent uint32                 `protobuf:"varint,6,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	EngineTempC    float32                `protobuf:"fixed32,7,opt,name=engine_temp_c,json=engineTempC,proto3" json:"engine_temp_c,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Telemetry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Telemetry) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Telemetry) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Telemetry) GetSpeedKmh() float32 {
	if x != nil {
		return x.SpeedKmh
	}
	return 0
}

func (x *Telemetry) GetBatteryPercent() uint32 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *Telemetry) GetEngineTempC() float32 {
	if x != nil {
		return x.EngineTempC
	}
	return 0
}

var File_vehicle_proto protoreflect.FileDescriptor

const file_vehicle_proto_rawDesc = "" +
	"\n" +
	"\rvehicle.proto\x12\avehicle\x1a\fcommon.proto\"\xdb\x01\n" +
	"\tTelemetry\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x1b\n" +
	"\tspeed_kmh\x18\x05 \x01(\x02R\bspeedKmh\x12'\n" +
	"\x0fbattery_percent\x18\x06 \x01(\rR\x0ebatteryPercent\x12\"\n" +
	"\rengine_temp_c\x18\a \x01(\x02R\vengineTempC2U\n" +
	"\x17VehicleTelemetryService\x12:\n" +
	"\x0fStreamTelemetry\x12\x12.vehicle.Telemetry\x1a\x0f.common.Command(\x010\x01B\x11Z\x0fproto/vehiclepbb\x06proto3"

var (
	file_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_proto_rawDescData []byte
)

func file_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)))
	})
	return file_vehicle_proto_rawDescData
}

var file_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vehicle_proto_goTypes = []any{
	(*Telemetry)(nil),        // 0: vehicle.Telemetry
	(*commonpb.Command)(nil), // 1: common.Command
}
var file_vehicle_proto_depIdxs = []int32{
	0, // 0: vehicle.VehicleTelemetryService.StreamTelemetry:input_type -> vehicle.Telemetry
	1, // 1: vehicle.VehicleTelemetryService.StreamTelemetry:output_type -> common.Command
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vehicle_proto_init() }
func file_vehicle_proto_init() {
	if File_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_proto_depIdxs,
		MessageInfos:      file_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_proto = out.File
	file_vehicle_proto_goTypes = nil
	file_vehicle_proto_depIdxs = nil
}
