// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: metrics.proto

package metricspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

type FleetMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalVehicles      uint32                 `protobuf:"varint,1,opt,name=total_vehicles,json=totalVehicles,proto3" json:"total_vehicles,omitempty"`
	ActiveVehicles     uint32                 `protobuf:"varint,2,opt,name=active_vehicles,json=activeVehicles,proto3" json:"active_vehicles,omitempty"`
	LowBatteryVehicles uint32                 `protobuf:"varint,3,opt,name=low_battery_vehicles,json=lowBatteryVehicles,proto3" json:"low_battery_vehicles,omitempty"`
	AvgSpeedKmh        float32                `protobuf:"fixed32,4,opt,name=avg_speed_kmh,json=avgSpeedKmh,proto3" json:"avg_speed_kmh,omitempty"`
	AvgEngineTempC     float32                `protobuf:"fixed32,5,opt,name=avg_engine_temp_c,json=avgEngineTempC,proto3" json:"avg_engine_temp_c,omitempty"`
	TimestampMs        int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FleetMetrics) Reset() {
	*x = FleetMetrics{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetrics) ProtoMessage() {}

func (x *FleetMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetrics.ProtoReflect.Descriptor instead.
func (*FleetMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *FleetMetrics) GetTotalVehicles() uint32 {
	if x != nil {
		return x.TotalVehicles
	}
	return 0
}

func (x *FleetMetrics) GetActiveVehicles() uint32 {
	if x != nil {
		return x.ActiveVehicles
	}
	return 0
}

func (x *FleetMetrics) GetLowBatteryVehicles() uint32 {
	if x != nil {
		return x.LowBatteryVehicles
	}
	return 0
}

func (x *FleetMetrics) GetAvgSpeedKmh() float32 {
	if x != nil {
		return x.AvgSpeedKmh
	}
	return 0
}

func (x *FleetMetrics) GetAvgEngineTempC() float32 {
	if x != nil {
		return x.AvgEngineTempC
	}
	return 0
}

func (x *FleetMetrics) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\"\a\n" +
	"\x05Empty\"\x82\x02\n" +
	"\fFleetMetrics\x12%\n" +
	"\x0etotal_vehicles\x18\x01 \x01(\rR\rtotalVehicles\x12'\n" +
	"\x0factive_vehicles\x18\x02 \x01(\rR\x0eactiveVehicles\x120\n" +
	"\x14low_battery_vehicles\x18\x03 \x01(\rR\x12lowBatteryVehicles\x12\"\n" +
	"\ravg_speed_kmh\x18\x04 \x01(\x02R\vavgSpeedKmh\x12)\n" +
	"\x11avg_engine_temp_c\x18\x05 \x01(\x02R\x0eavgEngineTempC\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs2O\n" +
	"\x0eMetricsService\x12=\n" +
	"\x12StreamFleetMetrics\x12\x0e.metrics.Empty\x1a\x15.metrics.FleetMetrics0\x01B\x11Z\x0fproto/metricspbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metrics_proto_goTypes = []any{
	(*Empty)(nil),        // 0: metrics.Empty
	(*FleetMetrics)(nil), // 1: metrics.FleetMetrics
}
var file_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.MetricsService.StreamFleetMetrics:input_type -> metrics.Empty
	1, // 1: metrics.MetricsService.StreamFleetMetrics:output_type -> metrics.FleetMetrics
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
