// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics.proto

package metricspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

type FleetMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveVehicles     uint32                 `protobuf:"varint,1,opt,name=active_vehicles,json=activeVehicles,proto3" json:"active_vehicles,omitempty"`
	OfflineVehicles    uint32                 `protobuf:"varint,2,opt,name=offline_vehicles,json=offlineVehicles,proto3" json:"offline_vehicles,omitempty"`
	LowBatteryVehicles uint32                 `protobuf:"varint,3,opt,name=low_battery_vehicles,json=lowBatteryVehicles,proto3" json:"low_battery_vehicles,omitempty"`
	AvgSpeedKmh        float32                `protobuf:"fixed32,4,opt,name=avg_speed_kmh,json=avgSpeedKmh,proto3" json:"avg_speed_kmh,omitempty"`
	AvgEngineTempC     float32                `protobuf:"fixed32,5,opt,name=avg_engine_temp_c,json=avgEngineTempC,proto3" json:"avg_engine_temp_c,omitempty"`
	TimestampMs        int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FleetMetrics) Reset() {
	*x = FleetMetrics{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetrics) ProtoMessage() {}

func (x *FleetMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetrics.ProtoReflect.Descriptor instead.
func (*FleetMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *FleetMetrics) GetActiveVehicles() uint32 {
	if x != nil {
		return x.ActiveVehicles
	}
	return 0
}

func (x *FleetMetrics) GetOfflineVehicles() uint32 {
	if x != nil {
		return x.OfflineVehicles
	}
	return 0
}

func (x *FleetMetrics) GetLowBatteryVehicles() uint32 {
	if x != nil {
		return x.LowBatteryVehicles
	}
	return 0
}

func (x *FleetMetrics) GetAvgSpeedKmh() float32 {
	if x != nil {
		return x.AvgSpeedKmh
	}
	return 0
}

func (x *FleetMetrics) GetAvgEngineTempC() float32 {
	if x != nil {
		return x.AvgEngineTempC
	}
	return 0
}

func (x *FleetMetrics) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// Per-vehicle snapshot for dashboards / TUI (full telemetry as last seen on server).
type VehicleSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VehicleId       uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Lat             float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon             float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	SpeedKmh        float32                `protobuf:"fixed32,4,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	BatteryPercent  uint32                 `protobuf:"varint,5,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	EngineTempC     float32                `protobuf:"fixed32,6,opt,name=engine_temp_c,json=engineTempC,proto3" json:"engine_temp_c,omitempty"`
	LastTelemetryMs int64                  `protobuf:"varint,7,opt,name=last_telemetry_ms,json=lastTelemetryMs,proto3" json:"last_telemetry_ms,omitempty"`
	Online          bool                   `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VehicleSnapshot) Reset() {
	*x = VehicleSnapshot{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleSnapshot) ProtoMessage() {}

func (x *VehicleSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleSnapshot.ProtoReflect.Descriptor instead.
func (*VehicleSnapshot) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleSnapshot) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *VehicleSnapshot) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *VehicleSnapshot) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *VehicleSnapshot) GetSpeedKmh() float32 {
	if x != nil {
		return x.SpeedKmh
	}
	return 0
}

func (x *VehicleSnapshot) GetBatteryPercent() uint32 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *VehicleSnapshot) GetEngineTempC() float32 {
	if x != nil {
		return x.EngineTempC
	}
	return 0
}

func (x *VehicleSnapshot) GetLastTelemetryMs() int64 {
	if x != nil {
		return x.LastTelemetryMs
	}
	return 0
}

func (x *VehicleSnapshot) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type FleetVehicles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*VehicleSnapshot     `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetVehicles) Reset() {
	*x = FleetVehicles{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetVehicles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetVehicles) ProtoMessage() {}

func (x *FleetVehicles) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetVehicles.ProtoReflect.Descriptor instead.
func (*FleetVehicles) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *FleetVehicles) GetVehicles() []*VehicleSnapshot {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *FleetVehicles) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\"\a\n" +
	"\x05Empty\"\x86\x02\n" +
	"\fFleetMetrics\x12'\n" +
	"\x0factive_vehicles\x18\x01 \x01(\rR\x0eactiveVehicles\x12)\n" +
	"\x10offline_vehicles\x18\x02 \x01(\rR\x0fofflineVehicles\x120\n" +
	"\x14low_battery_vehicles\x18\x03 \x01(\rR\x12lowBatteryVehicles\x12\"\n" +
	"\ravg_speed_kmh\x18\x04 \x01(\x02R\vavgSpeedKmh\x12)\n" +
	"\x11avg_engine_temp_c\x18\x05 \x01(\x02R\x0eavgEngineTempC\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\"\x82\x02\n" +
	"\x0fVehicleSnapshot\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x1b\n" +
	"\tspeed_kmh\x18\x04 \x01(\x02R\bspeedKmh\x12'\n" +
	"\x0fbattery_percent\x18\x05 \x01(\rR\x0ebatteryPercent\x12\"\n" +
	"\rengine_temp_c\x18\x06 \x01(\x02R\vengineTempC\x12*\n" +
	"\x11last_telemetry_ms\x18\a \x01(\x03R\x0flastTelemetryMs\x12\x16\n" +
	"\x06online\x18\b \x01(\bR\x06online\"h\n" +
	"\rFleetVehicles\x124\n" +
	"\bvehicles\x18\x01 \x03(\v2\x18.metrics.VehicleSnapshotR\bvehicles\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs2\x90\x01\n" +
	"\x0eMetricsService\x12=\n" +
	"\x12StreamFleetMetrics\x12\x0e.metrics.Empty\x1a\x15.metrics.FleetMetrics0\x01\x12?\n" +
	"\x13StreamFleetVehicles\x12\x0e.metrics.Empty\x1a\x16.metrics.FleetVehicles0\x01B\x11Z\x0fproto/metricspbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metrics_proto_goTypes = []any{
	(*Empty)(nil),           // 0: metrics.Empty
	(*FleetMetrics)(nil),    // 1: metrics.FleetMetrics
	(*VehicleSnapshot)(nil), // 2: metrics.VehicleSnapshot
	(*FleetVehicles)(nil),   // 3: metrics.FleetVehicles
}
var file_metrics_proto_depIdxs = []int32{
	2, // 0: metrics.FleetVehicles.vehicles:type_name -> metrics.VehicleSnapshot
	0, // 1: metrics.MetricsService.StreamFleetMetrics:input_type -> metrics.Empty
	0, // 2: metrics.MetricsService.StreamFleetVehicles:input_type -> metrics.Empty
	1, // 3: metrics.MetricsService.StreamFleetMetrics:output_type -> metrics.FleetMetrics
	3, // 4: metrics.MetricsService.StreamFleetVehicles:output_type -> metrics.FleetVehicles
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
