// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: vehicle.proto

package vehiclepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VehicleTelemetryService_StreamTelemetry_FullMethodName = "/vehicle.VehicleTelemetryService/StreamTelemetry"
)

// VehicleTelemetryServiceClient is the client API for VehicleTelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Streaming service for telemetry + commands
type VehicleTelemetryServiceClient interface {
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Telemetry, Command], error)
}

type vehicleTelemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVehicleTelemetryServiceClient(cc grpc.ClientConnInterface) VehicleTelemetryServiceClient {
	return &vehicleTelemetryServiceClient{cc}
}

func (c *vehicleTelemetryServiceClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Telemetry, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VehicleTelemetryService_ServiceDesc.Streams[0], VehicleTelemetryService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Telemetry, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VehicleTelemetryService_StreamTelemetryClient = grpc.BidiStreamingClient[Telemetry, Command]

// VehicleTelemetryServiceServer is the server API for VehicleTelemetryService service.
// All implementations must embed UnimplementedVehicleTelemetryServiceServer
// for forward compatibility.
//
// Streaming service for telemetry + commands
type VehicleTelemetryServiceServer interface {
	StreamTelemetry(grpc.BidiStreamingServer[Telemetry, Command]) error
	mustEmbedUnimplementedVehicleTelemetryServiceServer()
}

// UnimplementedVehicleTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVehicleTelemetryServiceServer struct{}

func (UnimplementedVehicleTelemetryServiceServer) StreamTelemetry(grpc.BidiStreamingServer[Telemetry, Command]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedVehicleTelemetryServiceServer) mustEmbedUnimplementedVehicleTelemetryServiceServer() {
}
func (UnimplementedVehicleTelemetryServiceServer) testEmbeddedByValue() {}

// UnsafeVehicleTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehicleTelemetryServiceServer will
// result in compilation errors.
type UnsafeVehicleTelemetryServiceServer interface {
	mustEmbedUnimplementedVehicleTelemetryServiceServer()
}

func RegisterVehicleTelemetryServiceServer(s grpc.ServiceRegistrar, srv VehicleTelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedVehicleTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VehicleTelemetryService_ServiceDesc, srv)
}

func _VehicleTelemetryService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VehicleTelemetryServiceServer).StreamTelemetry(&grpc.GenericServerStream[Telemetry, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VehicleTelemetryService_StreamTelemetryServer = grpc.BidiStreamingServer[Telemetry, Command]

// VehicleTelemetryService_ServiceDesc is the grpc.ServiceDesc for VehicleTelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehicleTelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vehicle.VehicleTelemetryService",
	HandlerType: (*VehicleTelemetryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _VehicleTelemetryService_StreamTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vehicle.proto",
}
